apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos
  namespace: tzchz
  selfLink: /apis/apps/v1/namespaces/tzchz/deployments/centos
  uid: f4c49d35-1681-4754-ae42-e64ad9d9b79a
  resourceVersion: "536468052"
  generation: 3
  creationTimestamp: 2020-07-16T07:43:44Z
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: centos
    spec:
      containers:
        - name: centos
          image: tutum/centos:latest
          ports:
            - containerPort: 22
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 5m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 3
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: "True"
      lastUpdateTime: 2020-07-16T07:43:47Z
      lastTransitionTime: 2020-07-16T07:43:47Z
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: "True"
      lastUpdateTime: 2020-07-16T07:43:47Z
      lastTransitionTime: 2020-07-16T07:43:44Z
      reason: NewReplicaSetAvailable
      message: ReplicaSet "centos-7dc765755b" has successfully progressed.
